#!/bin/zsh
# Daniel Kogan
# Wear a mask you fool

cdir="$(dirname "$0")"

cd "$(dirname "$0")"


source venv/bin/activate

for f in $(dirname "$0")/exe/*;  do 
  python protect.py $f
  new_name=${f%.png}
  new_name=${new_name}.mask.png
  echo $new_name
  mv $f $new_name

done

