#!/bin/zsh
# Wear a mask you fool

cdir="$(dirname "$0")"

cd "$(dirname "$0")"


FILES=exe/*

for f in $(dirname "$0")/exe/*;  do 
  python protect.py $f
  new_name=${f%.png}
  echo $new_name
  #mv $f $new_name.mask.png

done

