#!/bin/zsh
# Daniel Kogan
# 7/25/2020
# Set all images to paul.png, undoing effects of COVID-19 and mask

cdir="$(dirname "$0")"

cd "$(dirname "$0")"


FILES=exe/*

for f in $(dirname "$0")/exe/*;  do 
  cat paul.png > $f
  new_name=${f%.mask.png}
  new_name=${new_name}.png
  mv $f $new_name

done

